/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Review {
  reviewer: string;
  rating: number;
  comment: string;
  date: string;
}
export interface Product {
  id: string;
  name: string;
  description: string;
  shortDescription: string;
  price: number;
  discountPrice: [] | [number];
  category: string;
  image: string;
  image2: string;
  image3: string;
  image4: string;
  featured: boolean;
  newArrival: boolean;
  isBestSeller: boolean;
  sizes: string[];
  colors: string[];
  colorImages: Array<[string, string]>;
  stock: bigint;
  fabric: string;
  rating: number;
  reviewCount: bigint;
  soldCount: bigint;
  deliveryThreshold: bigint;
  returnDays: bigint;
  reviews: Review[];
  keyHighlights: string[];
  viewingCount: bigint;
  trendingBadge: boolean;
}
export interface OrderItem {
  productName: string;
  size: string;
  qty: bigint;
  price: number;
}
export interface Order {
  id: string;
  date: string;
  customerName: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  postalCode: string;
  paymentMethod: string;
  items: OrderItem[];
  productTotal: number;
  shippingFee: number;
  grandTotal: number;
  status: string;
  discountCode: string;
  discountAmount: number;
}
export interface Settings {
  storeName: string;
  whatsappNumber: string;
  easyPaisaNumber: string;
  contactEmail: string;
  deliveryFee: number;
  freeShippingThreshold: number;
  currency: string;
  heroImage: string;
  announcementCode: string;
  popupCode: string;
}
export interface Discount {
  code: string;
  percent: number;
  active: boolean;
  usageCount: bigint;
}
export interface Contact {
  id: string;
  name: string;
  email: string;
  phone: string;
  message: string;
  date: string;
}
export interface Subscriber {
  id: string;
  email: string;
  whatsapp: string;
  date: string;
}
export interface _SERVICE {
  getProducts: ActorMethod<[], Product[]>;
  addProduct: ActorMethod<[Product], string>;
  updateProduct: ActorMethod<[Product], boolean>;
  deleteProduct: ActorMethod<[string], boolean>;
  bulkImportProducts: ActorMethod<[Product[]], bigint>;
  seedProducts: ActorMethod<[Product[]], undefined>;
  getOrders: ActorMethod<[], Order[]>;
  getOrderById: ActorMethod<[string], [] | [Order]>;
  addOrder: ActorMethod<[Order], string>;
  updateOrderStatus: ActorMethod<[string, string], boolean>;
  getSettings: ActorMethod<[], Settings>;
  saveSettings: ActorMethod<[Settings], boolean>;
  getDiscounts: ActorMethod<[], Discount[]>;
  addDiscount: ActorMethod<[Discount], boolean>;
  updateDiscount: ActorMethod<[Discount], boolean>;
  deleteDiscount: ActorMethod<[string], boolean>;
  validateDiscount: ActorMethod<[string], [] | [number]>;
  getContacts: ActorMethod<[], Contact[]>;
  addContact: ActorMethod<[Contact], string>;
  deleteContact: ActorMethod<[string], boolean>;
  getSubscribers: ActorMethod<[], Subscriber[]>;
  addSubscriber: ActorMethod<[Subscriber], string>;
  deleteSubscriber: ActorMethod<[string], boolean>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
