/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    getProducts(): Promise<any[]>;
    addProduct(product: any): Promise<string>;
    updateProduct(product: any): Promise<boolean>;
    deleteProduct(id: string): Promise<boolean>;
    bulkImportProducts(products: any[]): Promise<bigint>;
    seedProducts(products: any[]): Promise<void>;
    getOrders(): Promise<any[]>;
    addOrder(order: any): Promise<string>;
    updateOrderStatus(id: string, status: string): Promise<boolean>;
    getSettings(): Promise<any>;
    saveSettings(settings: any): Promise<boolean>;
    getDiscounts(): Promise<any[]>;
    addDiscount(discount: any): Promise<boolean>;
    updateDiscount(discount: any): Promise<boolean>;
    deleteDiscount(code: string): Promise<boolean>;
    validateDiscount(code: string): Promise<[] | [number]>;
    getContacts(): Promise<any[]>;
    addContact(contact: any): Promise<string>;
    deleteContact(id: string): Promise<boolean>;
    getSubscribers(): Promise<any[]>;
    addSubscriber(subscriber: any): Promise<string>;
    deleteSubscriber(id: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(_secret: string): Promise<void> {}
    async getProducts() { return this.actor.getProducts(); }
    async addProduct(p: any) { return this.actor.addProduct(p); }
    async updateProduct(p: any) { return this.actor.updateProduct(p); }
    async deleteProduct(id: string) { return this.actor.deleteProduct(id); }
    async bulkImportProducts(ps: any[]) { return this.actor.bulkImportProducts(ps); }
    async seedProducts(ps: any[]) { return this.actor.seedProducts(ps); }
    async getOrders() { return this.actor.getOrders(); }
    async addOrder(o: any) { return this.actor.addOrder(o); }
    async updateOrderStatus(id: string, status: string) { return this.actor.updateOrderStatus(id, status); }
    async getSettings() { return this.actor.getSettings(); }
    async saveSettings(s: any) { return this.actor.saveSettings(s); }
    async getDiscounts() { return this.actor.getDiscounts(); }
    async addDiscount(d: any) { return this.actor.addDiscount(d); }
    async updateDiscount(d: any) { return this.actor.updateDiscount(d); }
    async deleteDiscount(code: string) { return this.actor.deleteDiscount(code); }
    async validateDiscount(code: string) { return this.actor.validateDiscount(code); }
    async getContacts() { return this.actor.getContacts(); }
    async addContact(c: any) { return this.actor.addContact(c); }
    async deleteContact(id: string) { return this.actor.deleteContact(id); }
    async getSubscribers() { return this.actor.getSubscribers(); }
    async addSubscriber(s: any) { return this.actor.addSubscriber(s); }
    async deleteSubscriber(id: string) { return this.actor.deleteSubscriber(id); }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
